#include "plexus/tools/mcap_schema.h"

#include "plexus/hints/robotics.h"

#include <string>
#include <cstdint>
#include <utility>
#include <optional>

// The single translation unit that names a vendor. It joins a neutral robotics concept hint to a
// Foxglove well-known JSON Schema so a compliant viewer decodes and plots the channel. The schema
// documents are copied verbatim (whitespace-compacted) from foxglove/foxglove-sdk
// schemas/jsonschema as consumer-supplied string data — not a linked dependency. A hint that maps
// to no schema (including the 0 sentinel) returns nullopt so the transcode's opaque schemaId-0
// path engages.

namespace plexus::tools {

namespace {

namespace robotics = plexus::hints::robotics;

constexpr const char *k_pose_schema =
    R"J({"title":"foxglove.Pose","description":"A position and orientation for an object or reference frame in 3D space","$comment":"Generated by https://github.com/foxglove/foxglove-sdk","type":"object","properties":{"position":{"title":"foxglove.Vector3","description":"Point denoting position in 3D space","type":"object","properties":{"x":{"type":"number","description":"x component"},"y":{"type":"number","description":"y component"},"z":{"type":"number","description":"z component"}},"required":["x","y","z"]},"orientation":{"title":"foxglove.Quaternion","description":"Quaternion denoting orientation in 3D space","type":"object","properties":{"x":{"type":"number","description":"x value"},"y":{"type":"number","description":"y value"},"z":{"type":"number","description":"z value"},"w":{"type":"number","description":"w value"}},"required":["x","y","z","w"]}},"required":["position","orientation"]})J";

constexpr const char *k_frame_transform_schema =
    R"J({"title":"foxglove.FrameTransform","description":"A transform between two reference frames in 3D space. The transform defines the position and orientation of a child frame within a parent frame. Translation moves the origin of the child frame relative to the parent origin. The rotation changes the orientation of the child frame around its origin.\n\nExamples:\n\n- With translation (x=1, y=0, z=0) and identity rotation (x=0, y=0, z=0, w=1), a point at (x=0, y=0, z=0) in the child frame maps to (x=1, y=0, z=0) in the parent frame.\n\n- With translation (x=1, y=2, z=0) and a 90-degree rotation around the z-axis (x=0, y=0, z=0.707, w=0.707), a point at (x=1, y=0, z=0) in the child frame maps to (x=-1, y=3, z=0) in the parent frame.","$comment":"Generated by https://github.com/foxglove/foxglove-sdk","type":"object","properties":{"timestamp":{"type":"object","title":"time","properties":{"sec":{"type":"integer","minimum":0},"nsec":{"type":"integer","minimum":0,"maximum":999999999}},"description":"Timestamp of transform"},"parent_frame_id":{"type":"string","description":"Name of the parent frame"},"child_frame_id":{"type":"string","description":"Name of the child frame"},"translation":{"title":"foxglove.Vector3","description":"Translation component of the transform, representing the position of the child frame's origin in the parent frame.","type":"object","properties":{"x":{"type":"number","description":"x component"},"y":{"type":"number","description":"y component"},"z":{"type":"number","description":"z component"}},"required":["x","y","z"]},"rotation":{"title":"foxglove.Quaternion","description":"Rotation component of the transform, representing the orientation of the child frame in the parent frame","type":"object","properties":{"x":{"type":"number","description":"x value"},"y":{"type":"number","description":"y value"},"z":{"type":"number","description":"z value"},"w":{"type":"number","description":"w value"}},"required":["x","y","z","w"]}},"required":["timestamp","parent_frame_id","child_frame_id","translation","rotation"]})J";

constexpr const char *k_compressed_image_schema =
    R"J({"title":"foxglove.CompressedImage","description":"A compressed image","$comment":"Generated by https://github.com/foxglove/foxglove-sdk","type":"object","properties":{"timestamp":{"type":"object","title":"time","properties":{"sec":{"type":"integer","minimum":0},"nsec":{"type":"integer","minimum":0,"maximum":999999999}},"description":"Timestamp of image"},"frame_id":{"type":"string","description":"Frame of reference for the image. The origin of the frame is the optical center of the camera. +x points to the right in the image, +y points down, and +z points into the plane of the image."},"data":{"type":"string","contentEncoding":"base64","description":"Compressed image data"},"format":{"type":"string","description":"Image format\n\nSupported values: `jpeg`, `png`, `webp`, `avif`"}},"required":["timestamp","frame_id","data","format"]})J";

// A well-known schema rides a json message channel, so the schema encoding is jsonschema.
mcap_schema well_known(std::string name, const char *data)
{
    return mcap_schema{"json", std::move(name), "jsonschema", data};
}

std::optional<mcap_schema> translate(std::uint64_t hint)
{
    if(hint == robotics::to_hint(robotics::kind::pose))
        return well_known("foxglove.Pose", k_pose_schema);
    if(hint == robotics::to_hint(robotics::kind::frame_transform))
        return well_known("foxglove.FrameTransform", k_frame_transform_schema);
    if(hint == robotics::to_hint(robotics::kind::compressed_image))
        return well_known("foxglove.CompressedImage", k_compressed_image_schema);
    return std::nullopt;
}

}

hint_translator well_known_schema_translator()
{
    return [](std::uint64_t hint) { return translate(hint); };
}

}
